name: Submit Assignment

on: [push, workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  submit:
    runs-on: ubuntu-latest
    env:
        project: '.LoongsonNeuq/LoongsonNeuq.AssignmentSubmit/LoongsonNeuq.AssignmentSubmit.csproj'

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout Submit Solution
      uses: actions/checkout@v4
      with:
        ref: 'submit-to-branch'
        repository: 'Loongson-neuq/LoongsonNeuq'
        path: '.LoongsonNeuq'
    
    - name: Restore Submit Solution
      run: dotnet restore ${{ env.project }}

    - name: Submit Assignment
      run: dotnet run --project ${{ env.project }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

