name: Submit Assignment

on: [push, workflow_dispatch]

jobs:
  submit:
    runs-on: ubuntu-latest
    env:
        URL: "https://github.com/Loongson-neuq/LoongsonNeuq/releases/download/assignment-submit-release/AssignmentSubmit.AppImage"
        SAVE_PATH: "AssignmentSubmit.AppImage"

    steps:
    - uses: actions/checkout@v4

    - name: Download AssignmentSubmit Binary
      run: wget ${{ env.URL }} -O ${{ env.SAVE_PATH }}

    - name: Grant Permission
      run: chmod +x ${{ env.SAVE_PATH }}

    - name: Submit Assignment
      run: ./${{ env.SAVE_PATH }} 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
